### ISSUE TITLE
Salary Information API

### ISSUE THREAD

**Issue by smarshallTGS** [TheAlphaSchoolSystemPTYLTD/payroll#3]
We are implementing a HRIS and would like to integrate the salary information from the HRIS into TASS.  Myself and the software provider have been advised this is possible. Can the information be shared for the API integration to occur?

**Comment by bradftass** [comment]
Hi, I understand this issue was escalated to our customer care manager who responded directly.  
At this stage, there is no ability to upload salary information into TASS due to the sensitive nature and calculations that take place within our Payroll system.

If you are able to provide details around what you require to upload into the system, these can be collected for future discussion in this area of the product.

**Comment by scottetass** [comment]
Hi,

This may be a consideration for the future but there are a lot of dependencies in this area that would need to be carefully considered.

Thanks, Scott
